# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UpSolo
                                 A QGIS plugin
 Upload pontos para o Servidor
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-24
        copyright            : (C) 2023 by André Costa
        email                : andre.costa@grupoge21.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UpSolo class from file UpSolo.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .up_solo import UpSolo
    return UpSolo(iface)
